name: CI

on: [ push ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      -
        name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: "cd ../.. && ./bin/rails server -p 3025 -b 0.0.0.0"
          wait-on: 'http://localhost:3025'
          wait-on-timeout: 10
          working-directory: system/cypress
          config-file: ../cypress.config.js
          project: '../..'
          record: false
          publish-summary: true
          component: false
