name: CI

on: [ push ]

jobs:

  install:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      -
        name: Set up Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails db:seed
      -
        name: Precompile Assets
        run: bin/rails assets:precompile
      -
        name: Run test suite
        run: bundle exec rake
      -
        name: Start Rails server
        env:
          RAILS_LOG_TO_STDOUT: true
        run: |
          bin/rails server -e development -p 3025 -b 0.0.0.0 > rails_server.log 2>&1 &
          while ! nc -z localhost 3025; do sleep 1; done
      -
        name: Output Rails Server Log
        run: cat rails_server.log
      -
        name: Verify Rails Server Response
        run: |
          curl --request GET \
            --url http://localhost:3025/posts.json \
            --header 'Accept: application/json'
      -
        name: Check for Pending Migrations
        run: |
          bin/rails db:migrate:status
      -
        name: List Cypress Directory
        run: |
          tree -L 3 -I node_modules system/
      -
        name: Install Dependencies for Headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libdrm2 libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 \
            libpangocairo-1.0-0 libasound2 libatspi2.0-0 libgtk-3-0 libxcomposite1 libxshmfence1
      -
        name: Verify Chrome Installation
        run: google-chrome --version
      -
        name: Install Cypress
        run: |
          cd system/cypress
          npm ci
      -
        name: Run Cypress Tests
        run: |
          cd system/cypress
          npx cypress run --browser chrome
