name: CI

on: [ push ]

env:
  RAILS_ENV: test

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      -
        name: Set up Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      -
        name: Run test suite
        run: bundle exec rake
      -
        name: Start Rails server
        run: |
          bin/rails server -p 3025 -b 0.0.0.0 &
          while ! nc -z localhost 3025; do sleep 1; done
      -
        name: Install Cypress
        run: cd system && npm install cypress --save-dev
      -
        name: Run Cypress tests
        run: cd system && npx cypress run --browser chrome
