name: CI

on: [ push ]

env:
  RAILS_ENV: test

jobs:

  install:

    runs-on: ubuntu-latest

    # container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      -
        name: Set up Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      -
        name: Run test suite
        run: bundle exec rake
      -
        name: Start Rails server
        env:
          RAILS_LOG_TO_STDOUT: true
        run: |
          bin/rails server -p 3025 -b 0.0.0.0 &
          while ! nc -z localhost 3025; do sleep 1; done
      -
        name: Verify Rails Server Response
        run: |
          curl -I http://localhost:3025
      -
        name: Check for Pending Migrations
        run: |
          bin/rails db:migrate:status
      # -
      #   name: Install Cypress
      #   uses: cypress-io/github-action@v2
      #   with:
      #     runTests: false
      # -
      #   name: Install Cypress
      #   run: |
      #     cd system/cypress
      #     npm ci
      -
        name: List Cypress Directory
        run: |
          tree -L 3 -I node_modules system/
      # -
      #   name: Run Cypress Tests
      #   run: |
      #     cd system/cypress
      #     npx cypress run --browser chrome
      -
        name: Run Cypress UI Tests - Chrome
        uses: cypress-io/github-action@v6
        with:
          install: true
          # start: bin/rails server -p 3025 -b 0.0.0.0
          wait-on: "http://localhost:3025"
          wait-on-timeout: 120
          browser: chrome
          headed: false
          # record: true
          # parallel: true
          # group: "UI - Chrome"
          spec: e2e/*
          working-directory: system/cypress
        env:
          DEBUG: '@cypress/github-action'
          ACTIONS_STEP_DEBUG: true
